### PR TITLE
Ability to use a large number of streams

### PR DESCRIPTION
**Pull request by nyurik**
If streams parameter is a function, treats it
as a stream object generator. Calling that function
will create a new stream, or falsey value when done.

### CODE REVIEW

**Comment by feross** [comment]
Nice work!

In the future, don't change the package version in PRs. That's done at publish time because there might be other changes that go into the same release.

Also, in this case, it should be a minor (_.x._) release, not patch (_._.x) because of semantic versioning:

> MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
http://semver.org/

Released as 1.6.0.

**Comment by feross** [comment]
I also just added you as a GitHub collaborator :+1:

**Comment by mafintosh** [comment]
This is great! FYI I've fixed a minor bug when using this new feature and classic streams.

**Comment by feross** [comment]
Ah, good catch!

**Comment by nyurik** [comment]
Thanks!!!

**Pull request closed without merging**
