### PR TITLE
Insert HTTP(S) stream in multistream

### PR DESCRIPTION
**Pull request by strikeentco**
This would be very handy, for example, when you want to concat remote *.txt files.

Also it can be really helpful, when you need to send multipart/form-data with some remote and local files (it is my case).

Example:
```js
var MultiStream = require('multistream');

var streams = [
  require('https').request('https://example.com/1.txt'),
  fs.createReadStream(__dirname + '/2.txt'),
  fs.createReadStream(__dirname + '/3.txt'),
  require('https').request('https://example.com/4.txt')
];

MultiStream(streams).pipe(process.stdout) // => 1234
```

### CODE REVIEW

**Comment by feross** [comment]
Thanks for the PR, but can't you just wait for the 'response' event and pass that stream into `multistream`? This seems like scope creep to me.

@mafintosh thoughts?

**Comment by mafintosh** [comment]
I agree with @feross' comment that you should just pass in the response streams directly

**Comment by strikeentco** [comment]
Sure, but it'll looks more clear when `multistream` handle this for me, especially when I have more than one HTTP stream.

Then, in this case, it may be better to add `Promise` support on the `multistream` side?
```js
MultiStream.prototype._next = function() {
  var self = this
  self._current = null

  if (typeof self._queue === 'function') {
    self._queue(function(err, stream) {
      if (err) return self.destroy(err)
      self._gotNextStream(toStreams2(stream))
    })
  } else {
    var stream = self._queue.shift()
    if ((typeof stream === 'object' || typeof stream === 'function') && typeof stream.then === 'function') {
      return stream.then(function(res) {
        self._gotNextStream(toStreams2(res))
      }).catch(function(err) {
        self.destroy(err)
      })
    } else if (typeof stream === 'function') stream = toStreams2(stream())
    self._gotNextStream(stream)
  }
}
```

It's also can make usage more smooth and clean. In this case.
```js
var req = require('https').request('https://avatars1.githubusercontent.com/u/2401029');

var promise = new Promise(function (resolve, reject) {
  req.on('response', function(res) {
    resolve(res);
  }).end();
  req.on('error', function(err) {
    reject(err);
  });
});

Multistream([promise]);
```

**Comment by feross** [comment]
Sorry, looks like the consensus is to not merge this.

**Pull request closed without merging**
