### PR TITLE
Dropped Chunks

### PR DESCRIPTION
**Pull request by murphyproject**
This fix should solve issue #50

I hope, this can help. Any suggestions, edits and questions are welcomed.

### CODE REVIEW

**Comment by mafintosh** [comment]
Uh nice catch!

**Comment by mafintosh** [comment]
Don't know how to release this, but @feross could you do a patch bump for this?

**Comment by johnsusek** [comment]
Yes please!

**Comment by feross** [comment]
This was released as 4.0.1

**Pull request merged**
